version: "3.8"
services:
  database:
    container_name: database
    image: vmangos_database:latest
    build:
      context: database
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: wxB4ppfuLgZ5YCwdo79
    env_file:
      - ./config.env
    ports:
      - 3306:3306
    volumes:
      - ./database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - ./database/update-migrations.sh:/docker-entrypoint-initdb.d/update-migrations.sh:ro
      - ./database/datadir:/var/lib/mysql
      - ./database/database:/opt/database
      - ./builder/opt/core/sql:/opt/sql
    restart: unless-stopped

  realmd:
    container_name: realmd
    build:
      context: realmd
      dockerfile: Dockerfile
    image: vmangos_realmd:latest
    ports:
      - 3724:3724
    volumes:
      - ./realmd/opt/vmangos/bin/realmd:/opt/vmangos/bin/realmd
      - ./realmd/opt/vmangos/etc/realmd.conf:/opt/vmangos/etc/realmd.conf:ro
      - ./realmd/opt/vmangos/logs:/opt/vmangos/logs
    depends_on:
      - database
    restart: unless-stopped

  mangosd:
    container_name: mangosd
    tty: true
    stdin_open: true
    ports:
      - 8085:8085
      - 7878:7878
    build:
      context: mangosd
      dockerfile: Dockerfile
    image: vmangos_mangosd:latest
    volumes:
      - ./mangosd/opt/vmangos/bin/mangosd:/opt/vmangos/bin/mangosd
      - ./mangosd/opt/vmangos/etc/mangosd.conf:/opt/vmangos/etc/mangosd.conf:ro
      - ./mangosd/opt/vmangos/logs:/opt/vmangos/logs
      - ./mangosd/opt/vmangos/honor:/opt/vmangos/honor
      - ./mangosd/opt/vmangos/warden_modules:/opt/vmangos/warden_modules:ro
      - ./data:/opt/vmangos/data:ro
    depends_on:
      - database
    restart: unless-stopped

  nginx-reverse-proxy:
    restart: always
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    ports:
      - 80:80
      - 433:443
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./nginx-reverse-proxy/certs:/etc/nginx/certs:ro
    restart: unless-stopped

  nginx-generator:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-generator
    volumes:
      - //var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-reverse-proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    volumes_from:
      - nginx-reverse-proxy
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx-reverse-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: unless-stopped

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-reverse-proxy
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx-reverse-proxy/certs:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-generator
    restart: unless-stopped

  php-fpm:
    image: php-fpm
    container_name: php-fpm
    build:
      context: php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./php-fpm:/usr/local/etc/php/php.ini


