FROM mariadb:latest

RUN apt-get update -y
RUN apt-get upgrade -y

RUN apt-get install -y apt-utils
RUN apt-get install -y mariadb-client
RUN apt-get install -y libmysqlclient-dev
RUN apt-get install -y libssl-dev
RUN apt-get install -y openssl
RUN apt-get install -y zlib1g-dev
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y p7zip-full
